config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :age, numericality: true 
  validates :name, :eye_color, :hair_color, length: { in: 2..25,
    message: "Please put a valid entry"
  }
  validates :gender, inclusion: {
    in: %w(Male Female),
    message: "Please either enter Male or Female"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def destroy
    Contact.find(params[:id]).destroy
    redirect_to contacts_path
  end

end

private

  def contact_params
    params.require(:contact).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/edit.html.erb
<h1>Edit Details</h1>
<%= form_for @contact do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>

<% end %>

app/views/contacts/index.html.erb
<h1> Contacts </h1>
<%= link_to 'Create A New Contact', new_contact_path %>
<% @contacts.each do |contact| %>
  <h2><%= contact.name %></h2>
  <%= link_to 'See Details', contact_path(contact) %>
  <%= link_to 'Edit Details', edit_contact_path(contact) %>
  <%= link_to 'Remove Contact', contact, method: :delete %>
<% end %>

app/views/contacts/new.html.erb
<h1>Create A New Contact</h1>
<%= form_for @contact do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.select :alive, [true, false] %>

  <%= f.submit %>

<% end %>

<%= link_to 'Cancel', contacts_path %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>
<h4>Gender: <%= @contact.age %></h4>
<p>Hair Color: <%= @contact.hair_color %></p>
<p>Eye Color: <%= @contact.eye_color %></p>
<p>Gender: <%= @contact.gender %></p>
<p>Currently living? <%= @contact.alive %></p>
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contacts', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Contact details</h1>
<p>Make or get all of the extremely important contact details here.</p>
<p>
  <%= link_to 'Start', contacts_path %>
</p>